sudo: true

language: python

cache: pip

matrix:
  include:
    - os: linux
    - python: '2.7'
      dist: trusty
      sudo: false
    - python: '3.5'
      dist: trusty
      sudo: false
    - python: '3.6'
      dist: trusty
      sudo: false
    - python: '3.7'
      dist: xenial
      sudo: true
    
  allow_failures:
    - python: '2.7'

before install:
  - chmod +x ./test/regression/run_cron_test.sh

install:
  - sudo apt-get update
  - pip install -r requirements-dev.txt
  - pip install jupyter
  - pip install .
  - pip freeze
  
  # Show all packages, for debugging

before_script:
  # Download gmsh
  - wget http://gmsh.info/bin/Linux/gmsh-2.11.0-Linux64.tgz
  - pwd
  - ls
  - tar xvf gmsh-2.11.0-Linux64.tgz

  # Create porepy config file
  - cd $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  - echo "config = {\"gmsh_path\":\"$TRAVIS_BUILD_DIR/gmsh-2.11.0-Linux/bin/gmsh\"} " > porepy_config.py
  # add $HOME to $PYTHONPATH to make config file accessible
  - export PYTHONPATH=${TRAVIS_BUILD_DIR}:${PYTHONPATH}

script: 
  - python setup.py test
  - sh ./test/regression/run_cron_test.sh

after_success:
  - coveralls
